title: Suraj Suresh # your name (or website title) here
logo: "/Images/images.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm experienced in the field of the data analysis and skilled in Data Wrangling, Machine learning, Exploratory Analysis, Data Visaulization.</br>In 2019 I began this journey to pursue a career in Data Science, Since then I have extracted knowledge from various courses, Kaggle Notebooks, Podcasts and twitter etc. This page consists of all my notes and projects through out this journey. Feel Free to go through and provide feedback.
  <br><br>
  <a href="https://www.linkedin.com/in/machineteacher/" class="button">LinkedIn</a></br>
  <a href="https://github.com/Suraj-MachineTeacher" class="button">GitHub</a></br>
  
theme: jekyll-theme-minimal
google_analytics: UA-59007770-1 # your Google Analytics tracking ID here
