title: Suraj Suresh 
logo: "/Images/Logo.jpg?raw=true"
description: "This page explains the steps I have taken towards being a data scientist. I began this journey in 2019 and since then I'm extracting knowledge from multiple platforms eg courses, books, podcasts,twitter,youtube etc. 
Any feedback with respect to my projects is accepted and would love to understand your point of view."

theme: jekyll-theme-minimal
